// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFV_WcOnCKrtTPGN__8lYoFRz0TRwD8pY',
    appId: '1:747375922749:android:34579d83e6d6b8b6692454',
    messagingSenderId: '747375922749',
    projectId: 'gymsystem-94ee5',
    databaseURL: 'https://gymsystem-94ee5-default-rtdb.firebaseio.com',
    storageBucket: 'gymsystem-94ee5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByWBqPaQ-JHc7i29n5ujQIqcoqicIPWeQ',
    appId: '1:747375922749:ios:eeec0e5594daa46c692454',
    messagingSenderId: '747375922749',
    projectId: 'gymsystem-94ee5',
    databaseURL: 'https://gymsystem-94ee5-default-rtdb.firebaseio.com',
    storageBucket: 'gymsystem-94ee5.appspot.com',
    androidClientId: '747375922749-e2qastkim77htgrium5059aj1tpkomra.apps.googleusercontent.com',
    iosBundleId: 'com.nahr.baytFinder',
  );
}
